### ISSUE TITLE
Deprecation of / as division operator in dart sass 2.0

### ISSUE THREAD

**Issue by lizsugar** [mmistakes/jekyll-theme-basically-basic#168]
## Environment

- Basically Basic version: 1.4.5
- Ruby gem or remote theme version: ruby gem
- Jekyll version: 4.3.1
- Operating system: Windows and Linux

## Expected behavior

A smooth clean site build without any issues

## Steps to reproduce the behavior

Running `bundle exec jekyll build` results in errors being thrown regarding the / operator being deprecated.

[output.txt](https://github.com/mmistakes/jekyll-theme-basically-basic/files/10340235/output.txt)

I have attempted to resolve these issues on https://github.com/lizsugar/jekyll-theme-basically-basic/tree/dart-sass-2.0-updates, which now builds a site without errors.  However, I now end up with the font scaling no longer working right.

How it looks before / is turned into math.div():
<img width="1367" alt="site-normal" src="https://user-images.githubusercontent.com/187255/210453692-27a43e5a-6649-4476-8394-64a6699b728d.png">

How it looks afterwards:
<img width="1368" alt="site-small-font" src="https://user-images.githubusercontent.com/187255/210453720-cc63bc5f-abfb-4631-9a65-1ce492053dd9.png">

I'm not familiar enough with the project to understand exactly how it was doing that scaling before.  If someone could help me out here, that'd be super great :)

**Comment by mmistakes** [comment]
Most of what I’m seeing in the output are warnings about Sass deprecations. The Sass in this project isn’t compatible with Dart Sass as it’s quite old so that’s likely why you’re seeing warnings and issues. 

Jekyll has some notes about it, you may need to use the older (and deprecated) Ruby Sass.
https://jekyllrb.com/news/2022/12/21/jekyll-sass-converter-3.0-released/

Here’s an issue on how to lock Jekyll’s Sass converter gem to the older version which should hopefully get around the errors.
https://github.com/jekyll/jekyll-sass-converter/issues/145#issuecomment-1363069829

Other than that the Sass partials would need to be refactored to support Dart Sass which isn’t something I will be getting to anytime soon.

As far as the [fluid type partial](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_sass/basically-basic/functions/_fluid-type.scss). More context there on its inner workings can be found here:
https://www.madebymike.com.au/writing/fluid-type-calc-examples/

**Comment by lizsugar** [comment]
Even better lol.  Thank you so much for the quick response!
