### ISSUE TITLE
CV Not working for me

### ISSUE THREAD

**Issue by twhite96** [mmistakes/jekyll-theme-basically-basic#18]
I have generated a `cv.json` file, placed it in `_data` yet it still doesn't render. Just shows up with nothing on it.

I think this is because I am not exactly sure where the path is supposed to be.

Repo: https://github.com/twhite96/new_resume

My `layout: cv` and `default: pages`. It's using the blog post default. Not sure what I am doing wrong.

**Comment by mmistakes** [comment]
You need to create a new page that has `layout: cv`. I'm not seeing that in your repo at all. Just two index pages ([index.html](https://github.com/twhite96/new_resume/blob/master/index.html) and [index.md](https://github.com/twhite96/new_resume/blob/master/index.md)) which you'll probably want to reconcile since they'll just overwrite each other.

Here's an example of the [CV/resume page](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/docs/cv.md) used on the theme's demo. You can call it whatever you want, give it whatever permalink/path you want. As long as it has `layout: cv` it'll pull in the `cv.json` data file.

**Comment by twhite96** [comment]
Okay that's done but it is not pulling in my cv. Where do I put the cv file? In the root folder or where?

**Comment by twhite96** [comment]
Nevermind. Edited the original index file and it is working.
