### ISSUE TITLE
Deprecation warnings. 

### ISSUE THREAD

**Issue by xinghengwang** [mmistakes/jekyll-theme-basically-basic#21]
I am keeping seeing deprecation warnings like this: 

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("variable-exists")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("variable-exists")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("mixin-exists")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("variable-exists")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("variable-exists")) instead.

DEPRECATION WARNING: Passing a string to call() is deprecated and will be illegal
in Sass 4.0. Use call(get-function("mixin-exists")) instead.

**Comment by mmistakes** [comment]
The Susy 2.0 mixins used by the theme have Sass functions that will be deprecated in Sass 4 whenever that is released. 

They are only warnings and nothing you need to worry about right now. Eventually I'll update the theme to use Susy 3, which will eliminate these warnings.

**Comment by michaelkeenan** [comment]
A fast way to remove the deprecation warnings is to replace this line in _support.scss:

`$_pass: call(unquote("#{$_type}-exists"), $_i);`

With this:

`$_pass: call(get-function(unquote("#{$_type}-exists")), $_i);`

(Beware, my approach was the "change something and see if it seems to work" method, rather than the "understand it deeply and do the correct thing in a way that definitely won't break something" method.)
