### ISSUE TITLE
It cannot show the navigator "about" and "cv"

### ISSUE THREAD

**Issue by TurbulenceHlr** [mmistakes/jekyll-theme-basically-basic#32]
hello, when I fork this and I run it.The screen shows that only a home navigator.And github always email me that "The page build completed successfully, but returned the following warning for the `master` branch:

You are attempting to use a Jekyll theme, "jekyll-theme-basically-basic", which is not supported by GitHub Pages. " 
what should I do? 
and the first question looks like this
![2017-10-19 1 07 36](https://user-images.githubusercontent.com/30150851/31732108-f191d422-b3fc-11e7-8939-5faea5f355f8.png)

**Comment by mmistakes** [comment]
**Question 1:** You don't have any posts or pages in your repo, that's why you're not seeing them in the menu. Forking the repo only gets you the theme files. It's up to you to create an [About](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/docs/about.md) and [CV](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/docs/cv.md) (with data file) pages.

If you're unsure of how to do that [consult the documentation](https://github.com/mmistakes/jekyll-theme-basically-basic#layout-page) for the correct `layout` for each, or you can inspect the demo site's pages and copy/modify those. They are all located under the [`docs/` folder](https://github.com/mmistakes/jekyll-theme-basically-basic/tree/master/docs).

**Question 2:** GitHub Pages is giving you that error because they do not support 3rd party theme gems. The issue is related to [this line](https://github.com/mmistakes/jekyll-theme-basically-basic/blob/master/_config.yml#L32) `theme: jekyll-theme-basically-basic` in your `_config.yml`.

That signals to Jekyll to use a theme gem, which is why GitHub is giving you the warning. You've forked the theme so it's unnecessary, just remove it and the warning will go away.

**Comment by TurbulenceHlr** [comment]
Alright thank you for instruction patiently. For me it’s time to sleep now and I will be try it tomorrow.BTW, thanks again

**Comment by TurbulenceHlr** [comment]
but now the question is when I goes to my githubpages it shows that 404 not found pages.

**Comment by TurbulenceHlr** [comment]
sorry I know.I typed the wrong username.sorry for bothering

**Comment by TurbulenceHlr** [comment]
hello now it comes a new one.if I paste your /docs on my githubpages.
then I try to land the site. this is how the web shows （I'm a completely fish for building a web)
so I really dont understand some words .
![Uploading 屏幕快照 2017-10-19 下午1.14.38.png…]()
