### ISSUE TITLE
Adding search to the theme

### ISSUE THREAD

**Issue by pixelastic** [mmistakes/jekyll-theme-basically-basic#40]
Hello, I'm the author of the [jekyll-algolia](https://github.com/algolia/jekyll-algolia) plugin. `jekyll-algolia` lets you push the content of your Jekyll website to Algolia, so you can then add search capabilities directly from the front-end. (Full disclosure, I work at Algolia).

I've created [a live demo](https://community.algolia.com/jekyll-algolia-example/) of what it looks like on the `minima` default theme. I wondered if you would be interested in adding something similar to your awesome theme.

![image](https://user-images.githubusercontent.com/283419/34298290-5af9252a-e71d-11e7-8b2b-bcd08e51bcef.png)
[Animated gif of the previous example](https://community.algolia.com/jekyll-algolia/assets/images/minima-search-b197fe774c759dfa33a44798a2445422.gif)

The `minima` theme is nice for a starter, but I assume most people would like to switch to another theme pretty quickly. I really like yours as it is simple but yet extremely readable and customisable. If you think that would be a valuable addition to the theme, we can collaborate together on that.

Using Algolia requires an account (to get an appId and apiKey), but we provide forever-free community accounts that can hold up to 10k records. In the context of `jekyll-algolia`, one record will be created for each `<p>` of content. To give you an idea, I've been blogging for 5+ years and I'm only using 4k records so it's safe to assume it can be used for free for a long time :)

I've written an [extended tutorial](https://community.algolia.com/jekyll-algolia/blog.html) on how to integrate front-end search into `minima`, and you can find more information about the actual indexing part (pushing data from Jekyll to Algolia) [here](https://community.algolia.com/jekyll-algolia/getting-started.html). The documentation website is still a WIP but you should be able to find most of the info.

Let me know if you'd be interested in collaborating on that front, I'd be very happy to provide any help I can.

Cheers,

**Comment by DirtyF** [comment]
@pixelastic 😄 the demo you made is based on [jekyll/minima](https://github.com/jekyll/minima/)  but maybe @mmistakes is also interested to add a search option on one of his themes.

**Comment by pixelastic** [comment]
I know :)

I made a demo on `minima` because it's the default theme (I'll submit a PR for that, by the way). But I would also be very interested in adding search to other themes. As I said, I find this theme very readable :)

**Comment by mmistakes** [comment]
I think this is a good idea and something I'd be interested in adding. I'd like to give it some thought on how I'd do this as I'd like to have a search fallback option that is 100% GitHub Pages compatible. Just to cover those who can't install Jekyll plugins or don't want to added complexity of using something like Travis CI to get around GH Pages 3rd party plugin limitations.

My other theme [Minimal Mistakes](https://github.com/mmistakes/minimal-mistakes) recently added [search support](https://github.com/mmistakes/minimal-mistakes/pull/1383) for [Lunr.js](https://github.com/olivernn/lunr.js), so I'm thinking that would be a good fallback. Just need to think about how I want the config setup to look like for the user.

The MM theme could also benefit from adding support for jekyll-algolia, especially since it's way more popular than this theme :wink:.

I'll work on a proof of concept PR and ping you @pixelastic if I hit any issues.

**Comment by pixelastic** [comment]
Awesome. I didn't check that MM had a search page already :roll_eyes:. That makes it an even better candidate.

Lunr would make a very good fallback for people that don't want to setup a Travis account for GitHub pages. It will be less efficient in terms of typo-tolerance and amount of data searchable, but will still give great results.

Let me know how if you have any questions and I'd be happy to help any way I can.

**Comment by mmistakes** [comment]
In progress #48

**Comment by mmistakes** [comment]
Merged in #48

**Comment by mmistakes** [comment]
Basically Basic demo site with Algolia search enabled - <https://mmistakes.github.io/jekyll-theme-basically-basic-algolia-search/>
