### ISSUE TITLE
Broken website 

### ISSUE THREAD

**Issue by Funeoz** [mmistakes/jekyll-theme-basically-basic#74]
I changed the gem theme, I copied and modified all the needed files to my folder and on my repository : [https://github.com/Funeoz/techlovers](url). But my website is broken, I just see my images and svg icons.
My website is here : [https://funeoz.github.io/techlovers/](url)

When I browse to a post by typing the URL, I see 4 big svg icons then I can see my post.

**Comment by mmistakes** [comment]
Something is wrong with your CSS, that's why the site looks broken.
https://funeoz.github.io/techlovers/assets/stylesheets/main.css

If you view source of that file it's HTML for the page and not the CSS.

Also you can't use the theme as a gem on GitHub Pages. You'll need to set it as a [`remote_theme`](https://github.com/mmistakes/jekyll-theme-basically-basic#remote-theme) instead.

**Comment by mmistakes** [comment]
Yes, give it a try. GitHub is essentially building your site without a theme because it doesn't support 3rd party theme gems. That's why you need to configure it as a `remote_theme` in your _config,yml.

**Comment by Funeoz** [comment]
Ok, i'm doing that

**Comment by Funeoz** [comment]
That worked ! Thanks you so much !
