### ISSUE TITLE
White block at bottom of page with "night" skin

### ISSUE THREAD

**Issue by kubu4** [mmistakes/jekyll-theme-basically-basic#77]
![y1025_001](https://user-images.githubusercontent.com/4514104/47522237-ddc9c400-d849-11e8-88ca-a451beabc717.png)

It renders this way when being locally served as well.

## Environment

- Basically Basic version: 1.4.1
- Ruby gem or remote theme version: 
- Jekyll version:
- Git repository URL: https://github.com/RobertsLab/sams-notebook
- GitHub Pages hosted (if yes provide URL to site): https://robertslab.github.io/sams-notebook/
- Operating system: Ubuntu 16.04
- Browser: Firefox

## Expected behavior

Expect solid background color for entire layout.

**Comment by mmistakes** [comment]
Did you modify the theme files at all when forking? 

Because when I clone your repo, remove the duplicated `_layouts`, `_includes`, `assets` and `_sass` folders, install the theme as a [remote theme](https://github.com/mmistakes/jekyll-theme-basically-basic#github-pages-method) by adding `remote_theme: "mmistakes/jekyll-theme-basically-basic" to _config.yml, everything looks correct.

The white box disappears. Which tells me there's something different in your fork from the default theme.

![image](https://user-images.githubusercontent.com/1376749/47528046-25644600-d872-11e8-8591-e9b92b1902da.png)

**Comment by kubu4** [comment]
Firstly, thanks so much for checking this out!

> Did you modify the theme files at all when forking?

Unfortunately, I'm brand new to Jekyll, so I'm not hip to the lingo. I've modified some stuff, but I'm not sure which files constitute "theme files". So, the answer is: probably.

> remove the duplicated _layouts, _includes, assets and _sass folders

Which duplicates? When I look in my repo, I only see those folders in the root directory. Are you referring to removing the "duplicates" found in ```/example/*```?

Or, are you saying you performed the following steps:

1. Delete existing folders mentioned above.

2. Add ```remote_theme: "mmistakes/jekyll-theme-basically-basic"``` to ```_config.yml```.

3. Build site (or, push to GitHub).

**Comment by mmistakes** [comment]
By theme files I mean everything in the `_layouts`, `_includes`, `_sass` and `assets` folders. Looks like you directly copied all of them from theme's repo. This is fine, but it's better to remove all of those folders/files and install as a `remote_theme`.

Doing it this way you can upgrade without needing to copy over files from the theme. By "duplicates" i was referring to those folders. I would suggest you remove them all as it looks like you modified something in one of the layouts that broke the layout.

1. You can remove `example/` and `docs/` as well since those are used for testing and the demo site.
2. Add remote_theme: "mmistakes/jekyll-theme-basically-basic" to _config.yml.
3. Replace the contents of `Gemfile` with:
    ```ruby
    source "https://rubygems.org"
    gem "github-pages", group: :jekyll_plugins
    ```
4. Run `bundle install`

Doing this you can build the site locally using the exact same gems GitHub Pages does. This is good to test that everything is working as expected before pushing up to GitHub for them to host your site.

**Comment by kubu4** [comment]
Thanks! This definitely resolves the issue! 

However, now that I don't have those folders any more, two quick questions:

1. If I'd like to change to font that's used throughout the site, what do I do?

2. How does the site render without those folders?

**Comment by mmistakes** [comment]
Have a look over Jekyll's docs on [how themes work](https://jekyllrb.com/docs/themes/#understanding-gem-based-themes). When you install as a Ruby gem or remote theme those folders won't be in your repo anymore. They are pulled down and managed elsewhere to make updating easier.

The only reason you'd want to keep copies of these theme file in your repo is if you are [overriding them](https://github.com/mmistakes/jekyll-theme-basically-basic#overriding-includes-and-layouts).

If you want to change the font you can [do so here](https://github.com/mmistakes/jekyll-theme-basically-basic#google-fonts), and then you'll need to [change the CSS](https://github.com/mmistakes/jekyll-theme-basically-basic#customizing-sass-scss). Add any Sass variable changes or other declarations to this file. It will override what is bundled in the theme.
