### ISSUE TITLE
Lunr search not returning results in production, but works on local build

### ISSUE THREAD

**Issue by kubu4** [mmistakes/jekyll-theme-basically-basic#81]
## Environment

- Basically Basic version: 1.4.1
- Ruby gem or remote theme version:
- Jekyll version: jekyll-3.8.4
- Git repository URL: https://github.com/RobertsLab/sams-notebook
- GitHub Pages hosted (if yes provide URL to site): https://robertslab.github.io/sams-notebook/
- Operating system: Ubuntu 16.04 and 18.04

## Expected behavior

Lunr search should return search results.

## Steps to reproduce the behavior

Lunr search works fine on local build, but fails to return any results on production build using remote theme with GitHub Pages.

**Comment by mmistakes** [comment]
It's not working because the JavaScript isn't loading for the search index. If you look at the browser's inspector console you'll see errors.

![screen shot 2018-11-11 at 6 43 53 pm](https://user-images.githubusercontent.com/1376749/48319919-c62c6280-e5e1-11e8-8922-21a7ecd938e8.png)

The path is wrong, and looking at your _config.yml I noticed you're improperly setting `url` and `baseurl`.

You'll want to use the following instead:

```
baseurl: "/sams-notebook"
url: "https://robertslab.github.io"
```

**Comment by kubu4** [comment]
Doh! So sorry to bother you with this.

There's even a comment in the ```_config.yml``` file.  :no_mouth: 

Thanks for the quick response. 

Everything's great now!
